version: "3.7"

services:
  postgres:
    image: postgres:14
    container_name: product-engine-postgres
    ports:
      - '54323:5432'
    volumes:
      - ./.docker/database/postgresql/data/:/var/lib/postgresql/data
      - ./.docker/database/postgresql/initdb/:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_MULTIPLE_DATABASES=product_engine
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    tmpfs:
      - /var/lib/postgresql
    networks:
      - default

  redis:
    image: redis:alpine
    container_name: product-engine-redis
    restart: always
    ports:
      - '63793:6379'
    environment:
      - REDIS_PASSWORD=redis
    expose:
      - 6379
    networks:
      - default

volumes:
  db_data: {}

networks:
  default:
    driver: bridge
