apiVersion: skaffold/v1
kind: Config
metadata:
  name: dev-k8s-product-engine
build:
  local:
    push: false
  artifacts:
    - image: newerton/product-engine
      context: .
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.*"
            dest: .
