apiVersion: v1
kind: Service
metadata:
  namespace: nestjs-k8s-namespace
  name: product-engine
spec:
  ports:
    - port: 3003
      targetPort: 3003
      protocol: TCP
  selector:
    app: product-engine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nestjs-k8s-namespace
  name: product-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-engine
  template:
    metadata:
      labels:
        app: product-engine
    spec:
      imagePullSecrets:
         - name: registry-secret
      containers:
        - name: product-engine
          image: newerton/product-engine:latest
          ports:
            - containerPort: 3003
          envFrom:
            - secretRef:
                name: product-engine-k8s-secret
